blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/woodpecker-kit/woodpecker-transfer-data/issues
    about: Ask questions and discuss with other users.